### ISSUE TITLE
Integration of Travis CI?

### ISSUE THREAD

**Issue by clementval** [omni-compiler/omni-compiler#405]
Would you be interested to integrate Travis CI with the repository? This is a free continuous integration service that allows you to run tests and report directly on pull requests and pushes. 
The only thing to integrate it is to add a `.travis.yml` file that describe the things to do. 
If it is of interest to you, I can prepare this file for the integration. 

https://travis-ci.org

@h-murai @mitsuhisa-sato @mnakao

**Comment by mnakao** [comment]
Thank you for your comment.

I considered using Travis CI, but decided not to use it before.
Instead of Travis CI, we have used a machine for CI which has 16 CPU cores in AICS. 

The reason is that omni compiler has a lot of test programs.
The test programs execute in parallel, the time of which requires about 30 min. in AICS machine.
Perhaps, Travis CI provides a (virtual )machine which has only 2 cores, we think the CI time requires more time.

**Comment by clementval** [comment]
Hi Nakao-san, 

Agreed with you but it could be a nice alternative at least to run the front-end/back-end tests and so on. 
I mean, it's hard for external contributors like me to be sure that a PR will pass your tests as I'm not sure what you are running.

**Comment by mnakao** [comment]
OK. I understand. 
Please add to a .travis.yml file to use Travis CI.

**Comment by h-murai** [comment]
Now CI is available for omni-compiler/xcodeml-tools .
